export { SpectronClient, type SpectronConfig } from './client.js';
export {
	AuthError,
	errorFromResponse,
	NotFoundError,
	RateLimitError,
	ScopeError,
	ServerError,
	SpectronError,
	type SpectronErrorInit,
	ValidationError,
} from './errors.js';
export type {
	AttributeUpdate,
	ChatReply,
	ChunkJson,
	ChunkPageJson,
	ContextResult,
	DocumentJson,
	DocumentKeywordJson,
	DocumentKeywordsResponse,
	DocumentPageJson,
	DocumentStatus,
	Entity,
	EntityHistoryEntry,
	EntityRef,
	ExtractionResult,
	ForgetResult,
	GraphEvidenceJson,
	IngestProfile,
	KeywordDetailJson,
	KeywordDocumentJson,
	KeywordJson,
	KeywordPageJson,
	KeywordSearchHitJson,
	KeywordSearchResponseJson,
	KnowledgeLinkTarget,
	KnowledgeLinkUpsert,
	KnowledgeNodeFullJson,
	KnowledgeNodeListedJson,
	KnowledgeNodePageJson,
	KnowledgeNodeSearchHitJson,
	KnowledgeNodeSearchResponseJson,
	KnowledgeNodeUpsertRow,
	KnowledgeSummaryJson,
	MemoryCategory,
	MemoryHit,
	MemoryQueryResponse,
	ProfileResponse,
	QueryFilter,
	QueryHitChunkJson,
	QueryHitDocumentJson,
	QueryHitJson,
	QueryMode,
	QueryResponseJson,
	ReflectionResult,
	RelationUpdate,
	SessionInfo,
	StructuredState,
	TraceListResponse,
	TraceRecord,
	TraceStats,
	TraverseApiResponse,
	TraverseEdgeJson,
	TraverseNodeJson,
	TraverseStartJson,
	Turn,
	TurnRole,
	UploadResponse,
} from './models.js';
export {
	KeywordsNamespace,
	KnowledgeNamespace,
	NodesNamespace,
	type NodesUpsertArgs,
	type QueryArgs,
	type TraverseArgs,
	type UploadArgs,
} from './namespaces/knowledge.js';
export {
	EntitiesNamespace,
	LifecycleNamespace,
	MemoryNamespace,
	Session,
	SessionsNamespace,
	TracesNamespace,
} from './namespaces/memory.js';
export { backoffSchedule, shouldRetry } from './retry.js';
export {
	deserialiseScope,
	type ScopeWireEntry,
	serialiseScope,
} from './scope.js';
export {
	type BuildMultipartArgs,
	buildMultipart,
	DEFAULT_MAX_RETRIES,
	DEFAULT_TIMEOUT_MS,
	type FetchLike,
	HttpTransport,
	type HttpTransportConfig,
	quotePath,
	type RequestOptions,
	type SpectronFileInput,
} from './transport.js';
